[package]
name = "bbqueue"
version = "0.4.4"
description = "A SPSC, lockless, no_std, thread safe, queue, based on BipBuffers"
repository = "https://github.com/jamesmunns/bbqueue"
authors = ["James Munns <james.munns@ferrous-systems.com>"]
edition = "2018"
readme = "../README.md"

categories = [
    "embedded",
    "no-std",
    "memory-management",
]
license = "MIT OR Apache-2.0"


[package.metadata.docs.rs]
all-features = true

[dependencies]
generic-array = "0.13"
cortex-m = { version = "0.6.0", optional = true }
cfg-if = "0.1.10"
rand = { version = "0.7", optional = true }
once_cell = { version = "1.3.1", optional = true }

[features]
thumbv6 = ["cortex-m"]

# NOTE: This is only intended for test purposes and stress
# testing atomic ordering. You really don't want this feature.
chaos = ["std", "rand", "once_cell"]

# TODO: These don't really do anything anymore
atomic = []
std = []
