on:
  push:
    branches: [ bbqueue-ng ]
  pull_request:
    branches: [ bbqueue-ng ]

name: Integration Tests

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - rust: nightly
            build: ""
          - rust: nightly
            build: "--release"

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: ${{ matrix.build }} --features=short-potato --manifest-path bbqtest/Cargo.toml -- --nocapture
